ProyectoFinal/Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.DAL;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class ColorController : Controller
    {
        private OpticaContext db = new OpticaContext();

        // GET: Colors
        public ActionResult Index()
        {
            return View(db.Colores.ToList());
        }

        // GET: Colors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colores.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // GET: Colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ColorId,Descripcion")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Colores.Add(color);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(color);
        }

        // GET: Colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colores.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Colors/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ColorId,Descripcion")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Entry(color).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(color);
        }

        // GET: Colors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colores.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Colors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Color color = db.Colores.Find(id);
            db.Colores.Remove(color);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/EstiloController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.DAL;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class EstiloController : Controller
    {
        private OpticaContext db = new OpticaContext();

        // GET: Estilo
        public ActionResult Index()
        {
            return View(db.Estilos.ToList());
        }

        // GET: Estilo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estilo estilo = db.Estilos.Find(id);
            if (estilo == null)
            {
                return HttpNotFound();
            }
            return View(estilo);
        }

        // GET: Estilo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estilo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EstiloId,Descripcion")] Estilo estilo)
        {
            if (ModelState.IsValid)
            {
                db.Estilos.Add(estilo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estilo);
        }

        // GET: Estilo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estilo estilo = db.Estilos.Find(id);
            if (estilo == null)
            {
                return HttpNotFound();
            }
            return View(estilo);
        }

        // POST: Estilo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EstiloId,Descripcion")] Estilo estilo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estilo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estilo);
        }

        // GET: Estilo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estilo estilo = db.Estilos.Find(id);
            if (estilo == null)
            {
                return HttpNotFound();
            }
            return View(estilo);
        }

        // POST: Estilo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estilo estilo = db.Estilos.Find(id);
            db.Estilos.Remove(estilo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/TamañoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.DAL;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class TamañoController : Controller
    {
        private OpticaContext db = new OpticaContext();

        // GET: Tamaño
        public ActionResult Index()
        {
            return View(db.Tamaños.ToList());
        }

        // GET: Tamaño/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamaño tamaño = db.Tamaños.Find(id);
            if (tamaño == null)
            {
                return HttpNotFound();
            }
            return View(tamaño);
        }

        // GET: Tamaño/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tamaño/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TamañoId,Descripcion")] Tamaño tamaño)
        {
            if (ModelState.IsValid)
            {
                db.Tamaños.Add(tamaño);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tamaño);
        }

        // GET: Tamaño/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamaño tamaño = db.Tamaños.Find(id);
            if (tamaño == null)
            {
                return HttpNotFound();
            }
            return View(tamaño);
        }

        // POST: Tamaño/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TamañoId,Descripcion")] Tamaño tamaño)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tamaño).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tamaño);
        }

        // GET: Tamaño/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamaño tamaño = db.Tamaños.Find(id);
            if (tamaño == null)
            {
                return HttpNotFound();
            }
            return View(tamaño);
        }

        // POST: Tamaño/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tamaño tamaño = db.Tamaños.Find(id);
            db.Tamaños.Remove(tamaño);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.DAL;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class VentaController : Controller
    {
        private OpticaContext db = new OpticaContext();

        // GET: Venta
        public ActionResult Index()
        {
            var ventas = db.Ventas.Include(v => v.Cliente).Include(v => v.Usuario);

            
            //    var clientes = db.Clientes.ToList();
            //    var clienteItems = new List<SelectListItem>();
            //    foreach (var item in clientes)
            //    {
            //        clienteItems.Add(new SelectListItem
            //        {
            //            Text = item.NombreCompleto,
            //            Value = item.ClienteId.ToString()
            //        });
            //    }
            //    ViewBag.clienteItems = clienteItems;

            //var usuarios = db.Usuarios.ToList();
            //var usuarioItems = new List<SelectListItem>();
            //foreach (var item in usuarios)
            //{
            //    usuarioItems.Add(new SelectListItem
            //    {
            //        Text = item.NombreUsuario,
            //        Value = item.UsuarioId.ToString()
            //    });
            //}
            //ViewBag.usuarioItems = usuarioItems;

            return View(ventas.ToList());
        }

        // GET: Venta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Ventas.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // GET: Venta/Create
        public ActionResult Create()
        {
            //var model = new ProyectoFinal.ViewModels.VentaViewModel
            //{
            //    Venta = new Venta(),
            //    Clientes = new SelectList(this.UnitOfWork.RegionRepository.Get(), "Id", "Name")
            //};
            var clientes = new List<Cliente>();
            clientes = db.Clientes.ToList();

            ViewBag.ClienteId = new SelectList(clientes, "ClienteId", "NombreCompleto");
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "NombreUsuario");
            return View();
        }

        // POST: Venta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VentaId,ClienteId,UsuarioId,Fecha")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Ventas.Add(venta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteId = new SelectList(db.Clientes, "ClienteId", "Nombre", venta.ClienteId);
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "NombreUsuario", venta.UsuarioId);
            return View(venta);
        }

        // GET: Venta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Ventas.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "ClienteId", "Nombre", venta.ClienteId);
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "NombreUsuario", venta.UsuarioId);
            return View(venta);
        }

        // POST: Venta/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VentaId,ClienteId,UsuarioId,Fecha")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "ClienteId", "Nombre", venta.ClienteId);
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "NombreUsuario", venta.UsuarioId);
            return View(venta);
        }

        // GET: Venta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Ventas.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Venta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venta venta = db.Ventas.Find(id);
            db.Ventas.Remove(venta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Óptica</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-danger">
        <a class="navbar-brand" href="#">Optica</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item nav-link">
                    @Html.ActionLink("Inicio", "Index", "Home")                   
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Acerca de", "About", "Home")
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Contacto", "Contact", "Home")
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Catálogos
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-item">@Html.ActionLink("Productos", "Index", "Producto")</div>
                        <div class="dropdown-item">@Html.ActionLink("Clientes", "Index", "Cliente")</div>
                        <div class="dropdown-item">@Html.ActionLink("Colores", "Index", "Color")</div>
                        <div class="dropdown-item">@Html.ActionLink("Estilos", "Index", "Estilo")</div>
                        <div class="dropdown-item">@Html.ActionLink("Suscripciones", "Index", "Suscripcion")</div>
                        <div class="dropdown-item">@Html.ActionLink("Tamaños", "Index", "Tamaño")</div>
                        <div class="dropdown-item">@Html.ActionLink("Usuarios", "Index", "Usuario")</div>
                    </div>
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Ventas", "Index", "Venta")
                </li>
            </ul>
        </div>
    </nav>

    @*</nav>*@
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Óptica", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>


            </div>
        </div>

        <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                        <
                        <li>@Html.ActionLink("Suscripciones", "Index", "Suscripcion")</li>
                        <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                        <li>@Html.ActionLink("Ventas", "Index", "Venta")</li>
                    </ul>
                </div>    *@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Óptica</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>